config/routes.rb
Rails.application.routes.draw do
  get 'three_poc/humanoid'
  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  devise_scope :user do
    authenticated :user do
      root "dashboard/calendars#index", as: :authenticated_root
    end

    unauthenticated do
      root "devise/sessions#new", as: :unauthenticated_root
    end
  end

  get "/terms",   to: "static_pages#terms"
  get "/privacy", to: "static_pages#privacy"
  get "/help",    to: "static_pages#help"

  resources :workouts do
    collection do
      get :select_exercise
      get :by_date
      delete :by_date, action: :destroy_by_date
    end

    resources :workout_sets, only: [:update, :destroy] do
      get :edit_group, on: :collection
      patch :update_group, on: :collection
    end
  end

  resources :workout_sets, only: [:create]

  resources :cardio_workouts, only: [:new, :create] do
    resources :cardio_sets, only: [:update, :destroy] do
      get :edit_group, on: :collection
      patch :update_group, on: :collection
    end
  end

  resources :body_parts, only: [:index] do
    resources :exercises
  end

  resources :calendars, only: :index

  namespace :stats do
    get "graphs", to: "graphs#index"
    get "cardio_graphs", to: "cardio_graphs#index"
  end

  namespace :api do
    get :sample, to: "samples#index"
    resource :avatar, only: :show
    resources :events, only: :index
    resources :calendar_summaries, only: [:index]
  end

  namespace :dashboard do
    get "calendar", to: "calendars#index"
    get "report",   to: "reports#index"
    get "avatar",  to: "profiles#index"
    get "setting", to: "settings#index"
    
    namespace :settings do
      resource :profile, only: [:show, :edit, :update]
      resource :account, only: [:show]
      patch "account/email", to: "accounts#update_email", as: :account_update_email
      patch "account/password", to: "accounts#update_password", as: :account_update_password
    end

    resource :inquiry, only: [:new, :create]
  end

  get "dashboard/stats", to: "dashboard#stats"

  get "three_poc/humanoid", to: "three_poc#humanoid"

  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/cardio_workout.rb
class CardioWorkout < ApplicationRecord
  belongs_to :user
  has_many :cardio_sets, dependent: :destroy

  validates :performed_on, presence: true
end

app/controllers/cardio_workouts_controller.rb
class CardioWorkoutsController < ApplicationController
  before_action :authenticate_user!

  def new
    @exercise = current_user.exercises.find(params[:exercise_id])
    @date = params[:date]
    @cardio_workout = CardioWorkout.new(performed_on: @date)
    @cardio_set = @cardio_workout.cardio_sets.build
  end

  def create
    cardio_workout = CardioWorkoutCreationService.new(
      user: current_user,
      exercise_id: params[:exercise_id],
      date: params[:performed_on],
      sets_params: params[:sets]
    ).call

    redirect_to redirect_path_for(cardio_workout.performed_on),
                notice: "有酸素トレーニングを記録しました"
  rescue CardioWorkoutCreationService::CreationError => e
    @exercise = Exercise.for_user(current_user).find(params[:exercise_id])
    @date     = params[:performed_on]
    flash.now[:alert] = e.message
    render :new, status: :unprocessable_entity
  end

  private

  def cardio_workout_params
    params.permit(:exercise_id, :performed_on)
  end

  def cardio_set_params
    params.require(:cardio_set).permit(
      :distance,
      :duration,
      :calories,
      :pace,
      :memo
    )
  end

  def redirect_path_for(date)
    workout = current_user.workouts.find_by(workout_date: date)
    if workout
      workout_path(workout)
    else
      # show は date 表示が可能なので id はダミーにしない
      by_date_workouts_path(date: date) # もしくは show を date 対応にしているなら適宜
    end
  end
end

app/views/cardio_workouts/new.html.erb
<div class="exercise-title-card mb-3 p-3 position-relative text-center">
  <h3 class="m-0"><%= @exercise.name %></h3>

  <a
    href="#"
    data-bs-toggle="modal"
    data-bs-target="#help-cardio-modal"
    class="btn btn-secondary btn-sm position-absolute top-50 end-0 translate-middle-y me-3"
  >
    ？
  </a>
</div>

<div id="set_form_errors"></div>

<div class="exercise-card">

  <%= form_with url: cardio_workouts_path, method: :post do %>

    <%= hidden_field_tag :performed_on, @date %>
    <%= hidden_field_tag :exercise_id, @exercise.id %>

    <div data-controller="cardio-sets"
         data-cardio-sets-date-value="<%= @date %>">

      <div class="floating-back"
           data-action="click->cardio-sets#commitOrBack">←</div>

      <div data-cardio-sets-target="list">
      </div>

      <template data-cardio-sets-target="template">
        <div class="set-input-row mb-3 p-3 rounded"
             data-controller="cardio-set-create">

          <div class="set-number-label mb-2 fw-bold"
               data-cardio-sets-target="number">
            セット1
          </div>

          <%= render "cardio_sets/form_fields", set: nil %>
        </div>
      </template>

      <button type="button"
              class="btn btn-secondary w-100 mt-2"
              data-action="cardio-sets#add">
        ＋ セットを追加
      </button>

    </div>

  <% end %>

</div>

<%= render "shared/help/cardio" %>